# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e82747468544e05c36014bad1b69c5ee"
name = "customer-accounts-demo"
handle = "customer-accounts-demo"
application_url = "https://outlined-laundry-pockets-walter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yanyi-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://outlined-laundry-pockets-walter.trycloudflare.com/auth/callback",
  "https://outlined-laundry-pockets-walter.trycloudflare.com/auth/shopify/callback",
  "https://outlined-laundry-pockets-walter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
